api:
    resource: '.'
    type:     'api_platform'
    prefix: 'api'

admin:
    resource: '@AdminBundle/Controller/'
    type:     annotation
    prefix: 'admin'

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'
    prefix: 'api'

# app/config/routing.yml
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"