api:
    resource: '.'
    type:     'api_platform'
    prefix: 'api'

admin:
    resource: '@AdminBundle/Controller/'
    type:     annotation
    prefix: 'admin'

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'
